var porjectview = "	<!--查看项目-->	"
    + "	<div class='layui-tab layui-tab-brief' lay-filter='docDemoTabBrief' style='margin:0px 0px'>	"
    + "	    <ul class='layui-tab-title'>	"
    + "	        <li class='layui-this'>基本信息</li>	"
    + "	        <li>消落带信息</li>	"
    + "	        <li>测窗信息</li>	"
    + "	        <li>节理信息</li>	"
    + "	        <li>优势结构面</li>	"
    + "	        <li>玫瑰花</li>	"
    + "	        <li>测窗成图信息</li>	"
    + "	    </ul>	"
    + "	    <div class='layui-tab-content' style='margin:0px 0px'>	"
    + "	        <!--基本信息-->	"
    + "	        <div class='layui-tab-item layui-show'>	"
    + "	            <form class='layui-form' style='margin-top:0px' lay-filter='projectinfoviewform'>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <label class='layui-form-label'>项目名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='xmmc' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>中心经度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxjd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>中心纬度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxwd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md3'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>行政区划</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xzqdm' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md9'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>项目位置</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmwz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>开始时间</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmkssj' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>备注</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='bz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </form>	"
    + "	        </div>	"
    + "	        <!--消落带-->	"
    + "	        <div class='layui-tab-item'>	"
    +"	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='xiaoluodaiinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>面积</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='mianJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>纵长</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zhongChang' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>体积</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='tiJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>坡向</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='puoXiang' lay-verify='required|number'  autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>后缘高程</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='hygc' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>估算厚度</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='gshd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>名称</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='xmmc' readonly='readonly' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>得分</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='projectScore'  readonly='readonly' autocomplete='off'  class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>地层岩性</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyx' lay-verify='required' autocomplete='off' placeholder='请输入地层岩性' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dcyxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩体结构</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjg' lay-verify='required' autocomplete='off' placeholder='请输入岩体结构' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩层产状</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='yccz' lay-verify='required' autocomplete='off' placeholder='请输入岩层产状' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ycczScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ycczWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"

    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岸坡结构</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjg' lay-verify='required' autocomplete='off' placeholder='请输入岸坡结构' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='apjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>切割裂隙</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglx' lay-verify='required' autocomplete='off' placeholder='请输入切割裂隙' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='qglxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>地貌边界</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbj' lay-verify='required' autocomplete='off' placeholder='请输入地貌边界' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbjScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='dmbjWeight' lay-verify='required|number'  autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>变形迹象</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjx' lay-verify='required' autocomplete='off' placeholder='请输入变形迹象' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='bxjxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>岩体裂化</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlh' lay-verify='required' autocomplete='off' placeholder='请输入岩体裂化' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlhScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='ytlhWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>植被覆盖</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfg' lay-verify='required' autocomplete='off' placeholder='请输入植被覆盖' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	             <input type='text' name='zbfgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='editxiaoluodaisubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"

    + "	        </div>	"
    + "	        <!--测窗信息-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='windowtable-view' lay-filter='windowtable-view'></table>	"
    + "	        </div>	"
    + "	        <!--节理信息-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='jielitable-view' lay-filter='jielitable-view'></table>	"
    + "	        </div>	"
    + "	        <!--优势结构面-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <table class='layui-hide' id='jiegoutables-view' lay-filter='jiegoutables-view'></table>	"
    + "	        </div>	"
    + "	        <!--节理玫瑰花-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <div id='autodatachart' class='layui-tab-item layui-show' style='width:790px;height:540px;top:40px'></div>	"
    + "	        </div>	"
    + "	        <!--节理成图-->	"
    + "	        <div class='layui-tab-item'>	"
    + "	            <div> 斜坡体</div>"
    + "	        </div>	"

    + "	    </div>	"
    + "	</div>	";

var addNewproject = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='addprojectinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目名称</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmmc' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心经度</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxjd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心纬度</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxwd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>行政区划</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='provinceid' name='province' lay-verify='required'>	"
    + "	                <option value=''>省/市</option>	"
    + "	                <option value='0'>重庆市</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='cityid' name='city' lay-verify='required'>	"
    + "	                <option value=''>市辖区/县</option>	"
    + "	                <option value='0'>市辖区</option>	"
    + "	                <option value='1'>县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='districtid' name='district' lay-verify='required'>	"
    + "	                <option value=''>区/县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目位置</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmwz' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>开始时间</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' id='xmkssjid' name='xmkssj' lay-verify='date' placeholder='YYYY-MM-DD' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>备注</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='bz' placeholder='请输入' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
  
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='addprojectinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

var pdfWindow = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfWindowinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='windowIdSelectpdf'  lay-verify='required' name='windowId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>模型</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='modleIdSelect' name='modleId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:5px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfWindowsubmit' style='width:100px'>查询</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"
    + "	<div id='pdfwinchart' class='layui-tab-item layui-show' style='width:900px;height:600px'></div>	";

var pdfjieli = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfjieliinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='jieliIdSelectpdf'  lay-verify='required' name='jieliId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>是否闭合</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='checkbox' name='isClose' checked='' value='0' lay-verify='required'  lay-skin='switch' lay-text='是|否' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                  <label class='layui-form-label'>采集人</label>	"
    + "	                     <div class='layui-input-block'>	"
    + "	                        <input type='text' name='collector' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:35px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfjielisubmit' style='width:100px'>素描</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	" ;
var projietHtml = "	<div class='layui-tab layui-tab-brief' lay-filter='projecrListTuCeng'>								"
    + "		<ul class='layui-tab-title'>							"
    + "			<li lay-id='111' class='layui-this' style='width:30%;padding-top: 10px;'>项目列表</li>						"
    + "			<li lay-id='222' style='width:30%;padding-top: 10px;'>图层列表</li>						"
    + "		</ul>							"
    + "		<div class='layui-tab-content'>							"
    + "			<div class='layui-tab-item layui-show'>						"
    + "						<div id='projectbyarea'>			"
    + "						</div>			"
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <div id='prjlayerlist'></div>			"
    + "			</div>						"
    + "		</div>							"
    + "	</div>								";

var addNewXiePuo = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='addprojectinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>斜坡名称</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmmc' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>开始时间</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' id='xmkssjid' name='xmkssj' lay-verify='date' placeholder='YYYY-MM-DD' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>备注</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='bz' placeholder='请输入' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"

    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='addprojectinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

var xiePuoSteepHillHtml = "	<!--隐患识别-->	"
    + "	<div class='layui-tab layui-tab-brief'  style='margin:0px 0px'>	"
    + "	 <form class='layui-form' action='' style='margin-top:5px;margin-right:5px;' lay-filter='xiePuoSteepHillFilter'>	"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 5px;'><legend>地形地貌  <input type='text' name='dxdm' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'style='width:90px;' >岸坡坡度</label>	"
    + "	        <div class='layui-input-inline' style='width:160px;'>	"
    + "	            <select id='appdId' lay-filter='appdSelect'   name='appd' lay-verify='required'>	"
    + "                 <option value=''>请选择岸坡坡度</option>	"
    + "                 <option value='1/6'>16°-30°=>1/6</option>	"
    + "                 <option value='2/6'>31°-45°=>2/6</option>	"
    + "                 <option value='2/12'>46°-60°=>1/6</option>	"
    + "                 <option value='1/3'>61°-90°=>2/6</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(1)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '评判标注:因子值\n16°-30°:1/6\n31°-45°:2/6\n46°-60°:1/6\n61°-90°:2/6' />	"
    + "	        </div>	"

    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label' style='width:90px;' >岸坡结构</label>	"
    + "	        <div class='layui-input-inline' style='width:160px;'>	"
    + "	            <select id='apjgId' name='apjg' lay-filter='apjgSelect' lay-verify='required'>	"
    + "                 <option value=''>请选择岸坡结构</option>	"
    + "					<option value='1/11'>横向岸坡=>1/11</option>	"
    + "					<option value='3/11'>顺向岸坡=>3/11</option>	"
    + "					<option value='6/22'>逆向岸坡=>3/11</option>	"
    + "					<option value='2/11'>斜顺向岸坡=>2/11</option>	"
    + "					<option value='4/22'>斜逆向岸坡=>2/11</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(2)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '岩层倾角（α）、岩层倾向与岸坡倾向间的夹角（β）\n横向岸坡因子值:1/11评判标准:60°＜β≦120°，0°≦α≦90° \n顺向岸坡因子值:3/11评判标准:0°＜β≦30° \n逆向岸坡因子值:3/11评判标准:150°＜β≦180°\n斜顺向岸坡因子值:2/11评判标准:0°≦α≦90°，30°＜β≦60°\n斜逆向岸坡因子值:2/11评判标准:0°≦α≦90°,120°＜β≦150° ' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label' style='width:90px;' >斜坡边界</label>	"
    + "	        <div class='layui-input-inline' style='width:160px;'>	"
    + "	            <select id='xpbjId' name='xpbj' lay-filter='xpbjSelect' lay-verify='required'>	"
    + "                 <option value=''>请选择斜坡边界</option>	"
    + "					<option value='3/6'>明显  =>3/6	</option>	"
    + "					<option value='2/6'>较明显=>2/6</option>	"
    + "					<option value='1/6'>不明显=>1/6</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(3)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '明显=>因子值:3/6评判标准: 斜坡上游下游两边界长度均大于10m   \n较明显=>因子值:2/6评判标准: 斜坡上游或者下游有一边界大于10m   \n不明显=>因子值:1/6评判标准: 斜坡上游和下游边界长度均不超过10m \n ' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 10px;'><legend>地质构造 <input type='text' name='dzgz' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩性岩组</label>"
    + "        <div class='layui-input-inline' style='width:160px;'>"
    + "            <select id='yxyzId' name='yxyz' lay-filter='yxyzSelect' lay-verify='required'>"
    + "                 <option value=''>请选择岩性岩组</option>"
    + "					<option value='2/27'>D2y=>2/27</option>"
    + "					<option value='4/54'>P2=>2/27</option>"
    + "					<option value='3/27'>P3=>3/27</option>"
    + "					<option value='1/9'>S1=>3/27</option>"
    + "					<option value='6/81'>T1d1=>2/27</option>"
    + "					<option value='1/27'>T1d2=>1/27</option>"
    + "					<option value='2/18'>T1d3=>3/27</option>"
    + "					<option value='8/108'>T1d4=>2/27</option>"
    + "					<option value='10/135'>T1j1=>2/27</option>"
    + "					<option value='4/36'>T1j2=>3/27</option>"
    + "					<option value='5/45'>T1j3=>3/27</option>"
    + "					<option value='2/54'>T1j4=>1/27</option>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(4)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = 'D2y=>因子值:2/27\nP2=>因子值:2/27\nP3=>因子值:3/27\nS1=>因子值:3/27\nT1d1=>因子值:2/27\nT1d2=>因子值:1/27\nT1d3=>因子值:3/27\nT1d4=>因子值:2/27\nT1j1=>因子值:2/27\nT1j2=>因子值:3/27\nT1j3=>因子值:3/27\nT1j4=>因子值:1/27' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >软弱层</label>"
    + "        <div class='layui-input-inline' style='width:160px;'>"
    + "            <select id='rucId' name='ruc' lay-filter='rucSelect' lay-verify='required'>"
    + "                 <option value=''>请选择软弱层</option>"
    + "					<option value='3/5'>有=>3/5</option>"
    + "					<option value='2/5'>无=>2/5</option>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(5)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '有=>因子值:3/5\n无=>因子值:2/5' />"
    + "        </div>"
    + "    </div>"
    + "      <fieldset class='layui-elem-field layui-field-title' style='margin-top: 10px;'><legend>工程地质 <input type='text' name='gcdz' lay-verify='required|number'  readonly='readonly' style='border:none;width: 60px;margin-left: 20px;' /></legend></fieldset>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩体结构</label>"
    + "        <div class='layui-input-inline' style='width:160px;'>"
    + "            <select id='ytjgId' name='ytjg' lay-filter='ytjgSelect' lay-verify='required'>"
    + "                 <option value=''>请选择岩体结构</option>"
    + "					<option value='1/13'>块状 =>1/13	</option>"
    + "					<option value='2/26'>厚层状=>1/13	</option>"
    + "					<option value='3/39'>中厚层状=>1/13</option>"
    + "					<option value='2/13'>互层状=>2/13	</option>"
    + "					<option value='3/13'>薄层状=>3/13	</option>"
    + "					<option value='4/26'>碎裂状=>2/13	</option>"
    + "					<option value='6/26'>散体状=>3/13	</option>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(6)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '块状=>因子值:1/13,评判标准: 岩体发育完整，层间距＞100cm \n厚层状=>因子值:1/13,评判标准: 岩体较完整，层间距100cm~50cm\n中厚层状=>因子值:1/13,评判标准: 岩体较完整，层间距50cm~30cm \n互层状=>因子值:2/13,评判标准: 岩体较完整，层间距30cm~10cm \n薄层状=>因子值:3/13,评判标准: 岩体完整性差，层间距＜10cm  \n碎裂状=>因子值:2/13,评判标准: 岩体破碎，间距小于10cm      \n散体状=>因子值:3/13,评判标准: 岩体破碎，岩块夹岩屑或泥质物' />"
    + "        </div>"
    + "    </div>"



    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;'>岩体风化程度</label>"
    + "        <div class='layui-input-inline' style='width:160px;'>"
    + "            <select id='ytfhId' name='ytfh' lay-filter='ytfhSelect' lay-verify='required'>"
    + "                 <option value=''>请选择岩体风化程度</option>"
    + "					<option value='1/3'>微风化=>1/3</option>"
    + "					<option value='2/3'>中风化=>2/3</option>"
    + "            </select>"
    + "        </div>"
    //+ "        <div class='layui-input-inline' style='width:350px;'>"
    //+ "             <input type='text' name='ytfhrest' autocomplete='off' placeholder='请输入备注' class='layui-input' />"
    //+ "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(7)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '微风化 => 因子值: 1 / 3, 评判标准: 岩石岩质新鲜，\n沿着节理面有些铁锰质渲染的痕迹或略有变色，\n有少量的风化痕迹，没有疏松物质，\n矿物质和岩石的组织结构基本没发生改变\n中风化 => 因子值: 2 / 3, 评判标准: 岩石构造层理清晰，\n但被节理裂隙切割成岩块状，裂隙里填充着少量风化物；\n结构部分破坏，矿物质的成分基本没发生变化，\n只沿着节理面出现了次生矿物；锤击声音脆，\n岩体不容易击碎，用镐难挖掘，岩芯钻方可钻进。' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "        <label class='layui-form-label' style='width:90px;' >岩体劣化程度</label>"
    + "        <div class='layui-input-inline' style='width:160px;'>"
    + "            <select id='ytlhId' name='ytlh' lay-filter='ytlhSelect' lay-verify='required'>"
    + "                 <option value=''>请选择岩体劣化程度</option>"
    + "					<option value='1/6'>一般=>1/6</option>"
    + "					<option value='2/6'>较强烈=>2/6</option>"
    + "					<option value='3/6'>强烈=>3/6</option>"
    + "            </select>"
    + "        </div>"
    + "	        <div class='layui-input-inline' style='width:30px;'>	"
    + "	              <img src = '/Resources/img/survey/shangChuan.png' onclick='goShangChuan(8)'  style='height: 30px;width: 30px;margin-top: 5px;cursor:pointer'  title = '图片上传' />	"
    + "	        </div>	"
    + "        <div class='layui-input-inline' style='width:30px;'>"
    + "              <img src = '/Resources/img/survey/tiShi.png'  style='height: 24px;width: 24px;margin-top: 8px'  title = '一般=>因子值:1/6\n较强烈=>因子值:2/6\n强烈=>因子值:3/6' />"
    + "        </div>"
    + "    </div>"
    + "    <div class='layui-form-item'>"
    + "	            <label class='layui-form-label' style='width: 90px'>总分</label>	"
    + "	            <div class='layui-input-inline'>	"
    + "	                <input type='text' name='score' style='border:none;font-weight: bold;font-size: 24px;' lay-verify='required|number' autocomplete='off'  readonly='readonly' class='layui-input' />	"
    + "	           </div>	"
    + "    </div>"
    + "    <div class='layui-form-item'>"
   // + "	            <label class='layui-form-label' style='width: 90px'>结论</label>	"
    + "	            <div class='layui-input-inline' style='width:95%;margin-left: 10px' >	"
    + "	                <input type='text' name='jieLun' style='border:none;font-size: 20px;' lay-verify='required' autocomplete='off'  readonly='readonly' class='layui-input' />	"
    + "	           </div>	"
    + "    </div>"
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:150px;'>	"
    //+ "	            <button type='button' class='layui-btn layui-btn-normal' id='LAY-component-form-setval'>赋值</button> "
    //+ "	            <button type = 'button' class='layui-btn layui-btn-normal' id = 'LAY-component-form-getval' > 计算</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='xiePuoSteepHillFilterSubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	  </form>	"
    + "	</div>	";
var xiepoTable = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='queryXiepoinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>斜坡状态</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select name='jieLun'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性大'>斜坡消落区发生演化可能性大</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性中'>斜坡消落区发生演化可能性中</option>	"
    + "	                            <option value='斜坡消落区发生演化可能性小'>斜坡消落区发生演化可能性小</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div style='position:absolute;right:15px;'>	"
    + "	                    <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	                    <button type='submit' class='layui-btn' lay-submit='' lay-filter='queryXieposubmit' style='width:100px'>查询</button>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"
    
     + "	<script type='text/html' id='processedPatrolButon'>                                                      "
    //+ "           {{#  if(d.status != 0){ }}"
    //+ "		        <a class='layui-btn layui-btn-xs' lay-event='edit'>查看坡面</a>                       "
    //+ "          {{#  } }} "
    + "          {{#  if(d.srcList != ''){ }}"
    + "			    <a class='layui-btn layui-btn-xs layui-btn-xs' lay-event='detail'>查看图片</a>  "
    + "          {{#  } }} "
    + "		</script>                                                                             "
    + "	<table class='layui-hide' id='xiepotable-view' lay-filter='xiepotable-view'></table>	";

var srcChaKan =  "<ul id='xiepochakan'>                                       "
    + "    <li><img id='appdSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡坡度'></li> "
    + "    <li><img id='apjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岸坡结构'></li> "
    + "    <li><img id='xpbjSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='斜坡边界'></li> "
    + "    <li><img id='yxyzSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩性岩组'></li> "
    + "    <li><img id='rucSrcId'  style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='软弱层'></li> "
    + "    <li><img id='ytjgSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体结构'></li> "
    + "    <li><img id='ytfhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体风化程度'></li> "
    + "    <li><img id='ytlhSrcId' style='width:80px;margin-top: 20px; height:80px;margin-left: 10px' alt='岩体裂化程度'></li> "
    +"</ul>                                                 "      
